# ===============================
# Server
# ===============================
server.port=8083

# ===============================
# Application
# ===============================
spring.application.name=patient-service

# ===============================
# Database (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/patientdb
spring.datasource.username=patient_user
spring.datasource.password=patient_pass

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# ===============================
# Flyway
# ===============================
spring.flyway.enabled=true

# ===============================
# Eureka Client
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

